services:
    mysqldb:
        image: mysql:8.0.30
        container_name: mysqlcontainer
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
            - $HOME/database:/var/lib/mysql
        ports:
            - 3307:3306
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: patientsdb
            MYSQL_USER: admin
            MYSQL_PASSWORD: mehedi
            MYSQL_ROOT_PASSWORD: mehedi
            SERVICE_TAGS: dev
            SERVICE_NAME: mysqldb
        networks:
            - internalnet

    nodeapp:
        container_name: nodeappcontainer
        build: .
        image: nodeapp:v1
        environment:
            DB_HOST: mysqldb
            DB_USER: "root"
            DB_PASSWORD: "mehedi"
            DB_NAME: patientsdb
            DB_PORT: 3306
            DB_CONNECTION_LIMIT: 10
            SERVER_PORT: 5000
        ports:
            - 5000:5000
        expose:
            - 5000
        depends_on:
            - mysqldb
        networks:
            - internalnet

networks:
    internalnet:
        driver: bridge
